const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const out = path.join(root, 'deploy');

function ensureDir(dirPath) {
	if (!fs.existsSync(dirPath)) fs.mkdirSync(dirPath, { recursive: true });
}

function copyFile(src, dest) {
	ensureDir(path.dirname(dest));
	fs.copyFileSync(src, dest);
}

function copyDir(srcDir, destDir, filter = () => true) {
	if (!fs.existsSync(srcDir)) return;
	ensureDir(destDir);
	for (const entry of fs.readdirSync(srcDir)) {
		const src = path.join(srcDir, entry);
		const dest = path.join(destDir, entry);
		const stat = fs.statSync(src);
		if (!filter(entry, src, stat)) continue;
		if (stat.isDirectory()) copyDir(src, dest, filter);
		else copyFile(src, dest);
	}
}

function writeIndexTxt() {
	const text = `This folder is a clean deployment bundle for Netlify drag-and-drop.\n\nIncluded:\n- index.html, gallery.html, photo-detail.html, cart.html, contact.html, thankyou.html\n- legal/ (shipping.html, returns.html)\n- styles.css, finlogo.png\n- images/ (public images copied/generated by scripts)\n- photos/ (static per-photo pages for SEO-friendly product links)\n- feeds/merchant_feed.csv (Google Merchant Center feed)\n- sitemap.xml, robots.txt, _headers, _redirects\n\nDo not edit files here directly. Edit in project root and re-run:\n  node scripts/generate-gallery.js\n  node scripts/copy-images.js\n  node scripts/generate-photo-pages.js\n  node scripts/generate-gmc-source.js\n  node scripts/generate-merchant-feed.js\n  node scripts/prepare-deploy.js\n`;
	fs.writeFileSync(path.join(out, 'INDEX.txt'), text, 'utf8');
}

(function run() {
	ensureDir(out);
	// Root HTML
	['index.html', 'gallery.html', 'photo-detail.html', 'cart.html', 'contact.html', 'thankyou.html'].forEach(f => {
		const src = path.join(root, f);
		if (fs.existsSync(src)) copyFile(src, path.join(out, f));
	});

	// Legal pages
	copyDir(path.join(root, 'legal'), path.join(out, 'legal'));

	// Core assets/config
	['styles.css', 'finlogo.png', 'robots.txt', '_headers', '_redirects', 'sitemap.xml'].forEach(f => {
		const src = path.join(root, f);
		if (fs.existsSync(src)) copyFile(src, path.join(out, f));
	});

	// Generated/needed folders
	copyDir(path.join(root, 'images'), path.join(out, 'images'));
	copyDir(path.join(root, 'photos'), path.join(out, 'photos'));
	copyDir(path.join(root, 'feeds'), path.join(out, 'feeds'), (name, src, stat) => {
		if (stat.isDirectory()) return true;
		return name === 'merchant_feed.csv';
	});

	// Preview assets used by pages
	copyDir(path.join(root, 'canvas_previews'), path.join(out, 'canvas_previews'));
	copyDir(path.join(root, 'metal_previews'), path.join(out, 'metal_previews'));
	copyDir(path.join(root, 'acrylic_previews'), path.join(out, 'acrylic_previews'));

	writeIndexTxt();
	console.log('Prepared deploy/ for drag-and-drop.');
})();


